### ISSUE TITLE
Make MessageBufferU constructor public

### ISSUE THREAD

**Issue by slandelle** [msgpack/msgpack-java#210]
Some APIs, such as Akka's ByteString, only provide read-only ByteBuffers. It would be great to make MessageBufferU constructor public instead of package private so I can easily write a custom MessageInput in my own package.

Regards

**Comment by xerial** [comment]
Using `MessageBuffer.newBuffer` or `wrap` is not sufficient?

**Comment by slandelle** [comment]
@xerial No, I don't think so. Correct me if I'm wrong, but MessageBuffer seems to be deciding on the MessageBuffer implementation [in a static way](https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java#L208), based on what's available (JDK version, Unsafe, etc).

I am running on Hotspot JDK7/8, so regular `MessageBuffer` impl is always picked, even if the ByteBuffer is read only. But then, the constructor will [crash](https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java#L262).

**Comment by slandelle** [comment]
Actually, shouldn't newBuffer check if the ByteBuffer is readonly and then use the universal implementation?

**Comment by xerial** [comment]
Using two or more types of MessageBuffer slows down each method call due to TypeProfile genaration in JVM. So I favor to support Akka's read-only buffer in MessageBuffer.

**Comment by slandelle** [comment]
You mean JIT not being able to optimize dispatch?

**Comment by xerial** [comment]
Right. ByteBuffer based memory access goes through TypeProfile, which manages access counts of DirectByteBuffer and HeapByteBuffer methods. HeapByteBuffer, which is the default implementation of ByteBuffer, is used frequently inside Java. Even if DirectByteBuffer is mostly used inside MessageBuffer, due to frequent HeapByteBuffer usage, JIT compiler optimization cannot create any short cut to access DirectByteBuffer.getXXX methods. 

I know MessageBuffer's design does not follow the standards of Java programming, but speed has been the most important factor in designing msgpack-java v07.

If simply making the constructor of MessageBufferU public enables to use Akka's byte string, please send a pull request with a test code that uses Akka's library. msgpack-java's test codes are written in Scala, so it would be easy to write such a test. I would like to check whether such modification has any impact on performance.

**Comment by slandelle** [comment]
Thanks for the explanation, very interesting!

Will send a PR ASAP. Actually, it's not a real blocker for me, I just created a factory in msgpack's package. It's just not very clean.

**Comment by slandelle** [comment]
PR provided, cf #212
