### ISSUE TITLE
IntegerValue should capture the size of the integer

### ISSUE THREAD

**Issue by velvia** [msgpack/msgpack-java#38]
The MessagePack serialized format knows the size of an Int, whether it's 8, 16, 32, or 64 bits.  However the current IntegerValue class loses this information, and it forces the user to pick the right method, getShort, getInt, etc.   It would be nice for IntegerValue to capture the original size of the integer when deserializing, and the same thing when it serializes.

**Comment by xerial** [comment]
In the message pack specification, integer value just conveys 63-bit signed integer:
https://github.com/msgpack/msgpack/blob/master/spec.md#types-limitation

So to support checking the actual message format type, it would be better to add a method (e.g., Value.getMessageFormatType) or let MessageUnpacker return the last read MessageFormat type. I think the latter is appropriate since Value is a separate notion from MessageFormat.
