### ISSUE TITLE
What is the most efficient way to deserialize to HashMap

### ISSUE THREAD

**Issue by lsena** [msgpack/msgpack-java#619]
Hi,

I've been trying to understand what is the most efficient (i.e. fast) way to deserialize msgpack bytes to a HashMap<Integer, Float>.
That object will potentially be serialized from a dictionary in python/c#.
Since the object can potentially have thousands of keys and will be used for lookups, deserialization speed (and lookup speed for the final object) is extremely important.

Do you have a code example of how I could do it?
Thank you!

**Comment by komamitsu** [comment]
I think there are 2 options.

1. Deserialize bytes to `org.msgpack.value.impl.ImmutableMapValueImpl.ImmutableMapValueMap` by `org.msgpack.core.MessageUnpacker#unpackValue()`. The output map is a kind of association list internally. So it's O(n) for lookup. Also  the key and value are wrapped in MessagePack values.

```java
        MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(bytes);
        Map<Value, Value> valueMap = unpacker.unpackValue().asMapValue().map();
```

2. Deserialize byte to `java.util.HashMap` by `com.fasterxml.jackson.databind.ObjectMapper#readValue()` with `jackson-dataformat-msgpack`. I recommend this if you use it for a lot of lookups since it's O(1) although it might take more time for deserialization than the option#1.

```java
        ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
        Map<String, Object> map = mapper.readValue(bytes, new TypeReference<HashMap<String, Object>>() {});
```
